name: Release

on:
  pull_request:
  push:
    branches: ['master']
    tags: ['v*']
  schedule:
  - cron: '00 01 * * *'

jobs:
  release:
    name: release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.*'
    - run: dotnet publish -c Release .\OhmGraphite\
    - name: Set artifact name
      shell: bash
      working-directory: OhmGraphite\bin
      run: |
        echo "ARTIFACT_NAME=$(echo *.zip)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      with:
        path: OhmGraphite\bin\*.zip
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error
    - name: Release
      uses: softprops/action-gh-release@v0.1.13 # https://github.com/softprops/action-gh-release/issues/280
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: 'OhmGraphite\bin\*.zip'
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
